# Exercise 18 - passwd to df

In this exercise, I want you to create a data frame from a file that you wouldn’t normally think of as CSV but that fits the format fine: the Unix ```passwd``` file. This file, which is standard on Unix and Linux systems, contains usernames and passwords. Over the years, it has evolved such that it no longer contains the actual passwords. Although MacOS is based on Unix, it doesn’t use the ```passwd``` file for most user logins.

Specifically, do the following:
1. Create a data frame based on ```linux-etc-passwd.txt```. Notice that this file contains comment lines (starting with ```#```) and blank lines (which you should ignore). The field separator is ```:```.

2. Add column names: ```username```, ```password```, ```userid```, ```groupid```, ```name```, ```homedir```, and ```shell```.

3. Make the ```username``` column the data frame’s index.

In [1]:
import pandas as pd

passwd = pd.read_csv(
    filepath_or_buffer="./linux-etc-passwd.txt",
    sep=":", # indicate the field separator
    header=None,
    names=["username", "password", "userid", "groupid", "name", "homedir", "shell"], # name the columns
    skip_blank_lines=True, # ignore blank lines
    comment="#", # ignore comments
    index_col="username", # indicate dataframe's index
)

passwd.head(10)

         password  userid  groupid    name          homedir              shell
username
root            x       0        0    root            /root          /bin/bash
daemon          x       1        1  daemon        /usr/sbin  /usr/sbin/nologin
bin             x       2        2     bin             /bin  /usr/sbin/nologin
sys             x       3        3     sys             /dev  /usr/sbin/nologin
sync            x       4    65534    sync             /bin          /bin/sync
games           x       5       60   games       /usr/games  /usr/sbin/nologin
man             x       6       12     man   /var/cache/man  /usr/sbin/nologin
lp              x       7        7      lp   /var/spool/lpd  /usr/sbin/nologin
mail            x       8        8    mail        /var/mail  /usr/sbin/nologin
news            x       9        9    news  /var/spool/news  /usr/sbin/nologin

## Beyond the exercise

Now that we’ve seen how parameters to ```read_csv``` can help us turn CSV files into dataframes, here are a few exercises to further help you understand how to massage ```passwd``` file into various types of data frames:

* Ignore the ```password``` and ```groupid``` fields so they don’t appear in the data frame.

In [2]:
passwd = pd.read_csv(
    filepath_or_buffer="./linux-etc-passwd.txt",
    sep=":", # indicate the field separator
    header=None,
    names=["username", "password", "userid", "groupid", "name", "homedir", "shell"], # name the columns
    skip_blank_lines=True, # ignore blank lines
    comment="#", # ignore comments
    index_col="username", # indicate dataframe's
    usecols=["username", "userid", "name", "homedir", "shell"] # do not read password and groupid columns
)

passwd.head(10)

          userid    name          homedir              shell
username
root           0    root            /root          /bin/bash
daemon         1  daemon        /usr/sbin  /usr/sbin/nologin
bin            2     bin             /bin  /usr/sbin/nologin
sys            3     sys             /dev  /usr/sbin/nologin
sync           4    sync             /bin          /bin/sync
games          5   games       /usr/games  /usr/sbin/nologin
man            6     man   /var/cache/man  /usr/sbin/nologin
lp             7      lp   /var/spool/lpd  /usr/sbin/nologin
mail           8    mail        /var/mail  /usr/sbin/nologin
news           9    news  /var/spool/news  /usr/sbin/nologin

* Unix systems typically reserve user IDs below 1000 to special accounts. Show the nonspecial usernames in this ```passwd``` file.

In [5]:
non_especial_users = passwd.query("userid >= 1000")
non_especial_users

          userid                       name       homedir              shell
username
nobody     65534                     nobody  /nonexistent  /usr/sbin/nologin
user        1000                    user,,,    /home/user          /bin/bash
reuven      1001        Reuven M. Lerner,,,  /home/reuven          /bin/bash
genadi      1002      Genadi Reznichenko,,,  /home/genadi          /bin/bash
shira       1003          Shira Friedman,,,   /home/shira          /bin/bash
atara       1004   Atara Lerner-Friedman,,,   /home/atara          /bin/bash
shikma      1005  Shikma Lerner-Friedman,,,  /home/shikma          /bin/bash
amotz       1006   Amotz Lerner-Friedman,,,   /home/amotz          /bin/bash
git         1007                  GitLab,,,     /home/git          /bin/bash
deploy      1008                  Deploy,,,  /home/deploy          /bin/bash

* Immediately after logging into a Unix system, a command interpreter known as a _shell_ fires up. What are the different shells in this file?

In [10]:
shells = passwd["shell"].unique()
for shell in shells:
    print(shell)

/bin/bash
/usr/sbin/nologin
/bin/sync
/bin/false
/bin/sh
/bin/nologin